name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite executar o workflow manualmente pela interface do GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Chrome and ChromeDriver
      run: |
        # Instala Chrome
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Obtém a versão do Chrome
        CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1)
        echo "Detected Chrome version: $CHROME_VERSION"
        
        # Usa uma fonte alternativa para ChromeDriver
        CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        
        # Se a versão específica falhar, usa a versão mais recente
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        fi
        
        echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # Download e instalação
        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P ~/tmp
        unzip ~/tmp/chromedriver_linux64.zip -d ~/tmp
        sudo mv -f ~/tmp/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver
        
        # Verifica a instalação
        chromedriver --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run tests
      run: |
        behave
