name: Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite executar o workflow manualmente pela interface do GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip

    - name: Install Chrome and ChromeDriver
      run: |
        # Função para obter a versão do ChromeDriver compatível
        get_chromedriver_version() {
            local chrome_version=$1
            local major_version=$(echo "$chrome_version" | cut -d'.' -f1)
            
            # Tenta obter a versão específica com curl -fs, retornando vazio em caso de erro
            local version=$(curl -fs "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$major_version" || echo "")
            
            # Se não obteve a versão, usa a versão mais recente
            if [ -z "$version" ]; then
                version=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
            fi
            
            echo "$version"
        }

        # Instala Chrome
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

        # Obtém a versão do Chrome
        CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3)
        CHROME_MAJOR_VERSION=$(echo "$CHROME_VERSION" | cut -d'.' -f1)
        echo "Detected Chrome version: $CHROME_VERSION"

        # Obtém a versão do ChromeDriver
        CHROMEDRIVER_VERSION=$(get_chromedriver_version "$CHROME_VERSION")

        # Verifica se conseguiu obter a versão
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Erro: Não foi possível determinar a versão do ChromeDriver"
            exit 1
        fi

        echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"

        # Cria diretório temporário
        mkdir -p ~/tmp

        # Download do ChromeDriver
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O ~/tmp/chromedriver.zip

        # Verifica o download
        if [ ! -f ~/tmp/chromedriver.zip ]; then
            echo "Erro: Download do ChromeDriver falhou"
            exit 1
        fi

        # Descompacta
        unzip -q ~/tmp/chromedriver.zip -d ~/tmp

        # Move para o diretório correto
        sudo mv -f ~/tmp/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver

        # Limpa arquivos temporários
        rm -f ~/tmp/chromedriver.zip

        # Verifica a instalação
        chromedriver --version
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi
        
    - name: Install test dependencies
      run: |
        pip install behave selenium
        
    - name: Run tests
      run: |
        behave
      env:
        # Configurações de ambiente para testes
        DISPLAY: :99
